Sprint 6
yourchencore666/MovieQuiz-ios pull request #8
Opened 2022-10-18 06:56 UTC by yourchencore666

- индикатор загрузки и алерт ошибки
- загрузка изображения из сети вместо локальной фабрики
- не стал делать фичу меняющую размер изображения так как изображения приходят в корректном размере

2022-10-18 12:36 UTC, mmbabaev requested changes

2022-10-18 12:36 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.showNextQuestionOrResults()
после нажатия на "попробовать еще раз" должна произойти повторная попытка загрузки списка фильмов. Сейчас алерт просто пропадает

2022-10-18 12:36 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            let index = (0..<self.movies.count).randomElement() ?? 0
давайте уберем плейсхолдер из сториборда. Сейчас сначала показывается одна картинка до загрузки списка фильмов

2022-10-18 13:28 UTC, yourchencore666 commented
добавил новый коммит:

- убрал дефолтную картинку, саму вью покрасил в цвет бекграунда чтобы её не было видно
- добавил вычисляемое свойство для ссылки на картинку, для изменения её размера(после того как убрал дефолтную картинку картинки стали сжатые)
- добавил повторный запрос картинок из сети по нажатию кнопки в алерте с ошибкой: теперь если отключить интернет, словить алерт, включить интернет и нажать кнопку то алерт пропадёт и загрузятся картинки

2022-10-18 18:40 UTC, mmbabaev requested changes

2022-10-18 18:40 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> -        <image name="Defolt" width="335" height="502"/>
сама картинка осталась в проекте

2022-10-18 18:40 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
В реальной разработке лучше не коммитить лишний diff (строчки без смысла)

2022-10-18 18:40 UTC, mmbabaev commented on MovieQuiz/Models/MostPopularMovies.swift
> +            // создаем строку из адреса
форматирование съехало, можно использовать `cmd+A` + `control+I`

2022-10-18 18:40 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.showNextQuestionOrResults()
Важно: каждое ножатие на "Повторить еще раз" производит переход на следующий вопрос. Если нажать пять раз, то окажемся не на 1 вопросе

2022-10-19 07:48 UTC, yourchencore666 commented
Внес исправления:

- Удалил картинку из проекта
- Поправил форматирование
- Исправил баг со сдвигом вопросов при попытке загрузить вопросы в алерте:
Раньше при каждом нажатии на "Попробовать еще раз" запрашивался следующий вопрос и после 10 нажатий раунд завершался.
Теперь запрашивать можно хоть сколько раз, а когда появится сеть и картинка загрузится, то алерт пропадёт и начнется игра

2022-10-19 08:05 UTC, mmbabaev approved these changes

2022-10-19 08:35 UTC, merged